baseURL = "https://kalifornia909.info"
languageCode = "en"
DefaultContentLanguage = "en"
title = "My Tech Journey"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-176080397-1"

[params]
title = "/Home/Kalifornia909"
author = "Josh Gaede"
description = "Sharing my projects and passion for technology"
profilePicture = "images/me.jpg"
keywords = "Technology,Information Technology,Cyber Security"
favicon = "favicons/"
customCss = ["css/syntax.css"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
displayMode = "dark"
pygmentsCodeFences = true
pygmentsUseClasses = true


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fab-twitter"
title = "twitter"
url = "https://twitter.com/kalifornia909"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/joshua-gaede/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/zer0sense"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/josh_gaede/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Categories"
  weight = 400
  identifier = "categories"
  url = "/categories/"
