baseURL = "https://kalifornia909.info"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Kalifornia's Tech Wonderland"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 4

[params]
  title = "Kalifornia's Tech Wonderland"
  author = "Kalifornia909"
  copyright = "2020-{{ YEAR }}"
  #description = "Kalifornia909's Nerd Haven"
  profilePicture = "images/logo.jpg"
  keywords = ""
  favicon = "favicons/"
  # example ["css/custom.css"]
  customCss = []
  # example ["js/custom.js"]
  customJs = [] 
  mainSections = ["post"]
  images = ["images/site-feature-image.png"]
  doNotLoadAnimations = false
  # Form Spree Contact Form
  #contactFormAction = "https://formspree.io/f/your-form-hash-here"
  #contactFormReCaptcha = "your-site-key-here"
  # Google Fonts
  #googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
  # Google Site Verify
  #googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  singleDateFormat = "2/1/2006"
  indexDateFormat = "2/1/2006"
  listDateFormat = "2/1/2006"
  # Commento Comments
  # CommentoURL = "https://commento.example.com/js/commento.js"
  # Read More links for truncated summaries
  # readMore = true
  # postSectionName = "blog"
  relatedPosts = true
  numberOfRelatedPosts = 3


  reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

  # hidesidebar = true

  [simpleAnalytics]
  # enable = true
  # customurl = "https://analytics.example.com"

  [plausibleAnalytics]
  # domain = "example.com"
  # serverURL = "https://analytics.example.com"

  [umami]
  # serverURL = "example.com"
  # id = "94db1cb1-74f4-4a40-ad6c-962362670409"
  # trackerScriptName = "mycustomscriptname.js"

  ## Math settings
  [math]
  enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
  use = "katex"  # options: "katex", "mathjax". default is "katex".

  ## Social links
  # use 'fab' when brand icons, use 'fas' when standard solid icons.
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/joshua-gaede/"
  [[params.socialIcons]]
    icon = "fab fa-github"
    name = "Github"
    url = "https://github.com/zer0sense"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    name = "Twitter"
    url = "https://twitter.com/kalifornia909"

[mermaid]
  enable = true