baseURL = "https://kalifornia909.info"
languageCode = "en"
DefaultContentLanguage = "en"
title = "My Tech Journey"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

[params]
title = "Kalifornia909's Blog"
author = "Josh Gaede"
description = "Technology Projects and Tips"
profilePicture = "images/me.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
displayMode = "dark"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/joshua-gaede/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/zer0sense"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/josh_gaede/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/kalifornia909"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"